# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WvMainWindow3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 867)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, -1, 11, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 858, 793))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabsWohnung = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_3)
        self.tabsWohnung.setStyleSheet("")
        self.tabsWohnung.setObjectName("tabsWohnung")
        self.tabDetails = QtWidgets.QWidget()
        self.tabDetails.setObjectName("tabDetails")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabDetails)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.grpSonst = QtWidgets.QGroupBox(self.tabDetails)
        self.grpSonst.setObjectName("grpSonst")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grpSonst)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtBemerk = QtWidgets.QPlainTextEdit(self.grpSonst)
        self.txtBemerk.setMaximumSize(QtCore.QSize(16777215, 70))
        self.txtBemerk.setObjectName("txtBemerk")
        self.gridLayout_4.addWidget(self.txtBemerk, 2, 1, 1, 4)
        self.cboGarage = QtWidgets.QComboBox(self.grpSonst)
        self.cboGarage.setObjectName("cboGarage")
        self.cboGarage.addItem("")
        self.cboGarage.addItem("")
        self.cboGarage.addItem("")
        self.cboGarage.addItem("")
        self.gridLayout_4.addWidget(self.cboGarage, 1, 3, 1, 2)
        self.lblBemerk = QtWidgets.QLabel(self.grpSonst)
        self.lblBemerk.setObjectName("lblBemerk")
        self.gridLayout_4.addWidget(self.lblBemerk, 2, 0, 1, 1)
        self.cbAufzug = QtWidgets.QCheckBox(self.grpSonst)
        self.cbAufzug.setObjectName("cbAufzug")
        self.gridLayout_4.addWidget(self.cbAufzug, 1, 1, 1, 1)
        self.cbKeller = QtWidgets.QCheckBox(self.grpSonst)
        self.cbKeller.setObjectName("cbKeller")
        self.gridLayout_4.addWidget(self.cbKeller, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.grpSonst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.grpSonst, 2, 0, 1, 1)
        self.grpWhg = QtWidgets.QGroupBox(self.tabDetails)
        self.grpWhg.setObjectName("grpWhg")
        self.formLayout_3 = QtWidgets.QFormLayout(self.grpWhg)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lblZimmer = QtWidgets.QLabel(self.grpWhg)
        self.lblZimmer.setObjectName("lblZimmer")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblZimmer)
        self.spinBox = QtWidgets.QSpinBox(self.grpWhg)
        self.spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label = QtWidgets.QLabel(self.grpWhg)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.grpWhg)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.grpWhg)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.grpWhg)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.grpWhg)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.checkBox = QtWidgets.QCheckBox(self.grpWhg)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.label_7 = QtWidgets.QLabel(self.grpWhg)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.grpWhg)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_8 = QtWidgets.QLabel(self.grpWhg)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.grpWhg)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.gridLayout_3.addWidget(self.grpWhg, 1, 0, 1, 1)
        self.grpBad = QtWidgets.QGroupBox(self.tabDetails)
        self.grpBad.setObjectName("grpBad")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grpBad)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbTageslicht = QtWidgets.QCheckBox(self.grpBad)
        self.cbTageslicht.setObjectName("cbTageslicht")
        self.verticalLayout_2.addWidget(self.cbTageslicht)
        self.cbDusche = QtWidgets.QCheckBox(self.grpBad)
        self.cbDusche.setObjectName("cbDusche")
        self.verticalLayout_2.addWidget(self.cbDusche)
        self.cbWanne = QtWidgets.QCheckBox(self.grpBad)
        self.cbWanne.setObjectName("cbWanne")
        self.verticalLayout_2.addWidget(self.cbWanne)
        self.cbBidet = QtWidgets.QCheckBox(self.grpBad)
        self.cbBidet.setObjectName("cbBidet")
        self.verticalLayout_2.addWidget(self.cbBidet)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.grpBad, 1, 1, 1, 1)
        self.grpAdresse = QtWidgets.QGroupBox(self.tabDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpAdresse.sizePolicy().hasHeightForWidth())
        self.grpAdresse.setSizePolicy(sizePolicy)
        self.grpAdresse.setStyleSheet("")
        self.grpAdresse.setObjectName("grpAdresse")
        self.formLayout_2 = QtWidgets.QFormLayout(self.grpAdresse)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblPlz = QtWidgets.QLabel(self.grpAdresse)
        self.lblPlz.setObjectName("lblPlz")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblPlz)
        self.inPlz = QtWidgets.QLineEdit(self.grpAdresse)
        self.inPlz.setMaximumSize(QtCore.QSize(70, 16777215))
        self.inPlz.setObjectName("inPlz")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inPlz)
        self.lblOrt = QtWidgets.QLabel(self.grpAdresse)
        self.lblOrt.setObjectName("lblOrt")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblOrt)
        self.inOrt = QtWidgets.QLineEdit(self.grpAdresse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inOrt.sizePolicy().hasHeightForWidth())
        self.inOrt.setSizePolicy(sizePolicy)
        self.inOrt.setText("")
        self.inOrt.setObjectName("inOrt")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inOrt)
        self.lblStrasse = QtWidgets.QLabel(self.grpAdresse)
        self.lblStrasse.setObjectName("lblStrasse")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblStrasse)
        self.inStrasse = QtWidgets.QLineEdit(self.grpAdresse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inStrasse.sizePolicy().hasHeightForWidth())
        self.inStrasse.setSizePolicy(sizePolicy)
        self.inStrasse.setText("")
        self.inStrasse.setObjectName("inStrasse")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inStrasse)
        self.lblWhgBez = QtWidgets.QLabel(self.grpAdresse)
        self.lblWhgBez.setObjectName("lblWhgBez")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblWhgBez)
        self.inWhgBez = QtWidgets.QLineEdit(self.grpAdresse)
        self.inWhgBez.setMinimumSize(QtCore.QSize(150, 0))
        self.inWhgBez.setObjectName("inWhgBez")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inWhgBez)
        self.gridLayout_3.addWidget(self.grpAdresse, 0, 0, 1, 1)
        self.tabsWohnung.addTab(self.tabDetails, "")
        self.tabRechnungen = QtWidgets.QWidget()
        self.tabRechnungen.setAccessibleDescription("")
        self.tabRechnungen.setObjectName("tabRechnungen")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tabRechnungen)
        self.buttonBox.setGeometry(QtCore.QRect(510, 620, 189, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.btnTest = QtWidgets.QPushButton(self.tabRechnungen)
        self.btnTest.setGeometry(QtCore.QRect(260, 150, 89, 25))
        self.btnTest.setObjectName("btnTest")
        self.tabsWohnung.addTab(self.tabRechnungen, "")
        self.tabMiete = QtWidgets.QWidget()
        self.tabMiete.setObjectName("tabMiete")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabMiete)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 1, 1, 1)
        self.tbMieteGueltigAb = QtWidgets.QToolButton(self.tabMiete)
        self.tbMieteGueltigAb.setObjectName("tbMieteGueltigAb")
        self.gridLayout_2.addWidget(self.tbMieteGueltigAb, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 0, 1, 1)
        self.inNkAbschlag = QtWidgets.QLineEdit(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inNkAbschlag.sizePolicy().hasHeightForWidth())
        self.inNkAbschlag.setSizePolicy(sizePolicy)
        self.inNkAbschlag.setObjectName("inNkAbschlag")
        self.gridLayout_2.addWidget(self.inNkAbschlag, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.inMieteBemerkung = QtWidgets.QPlainTextEdit(self.tabMiete)
        self.inMieteBemerkung.setMaximumSize(QtCore.QSize(16777215, 60))
        self.inMieteBemerkung.setPlainText("")
        self.inMieteBemerkung.setObjectName("inMieteBemerkung")
        self.gridLayout_2.addWidget(self.inMieteBemerkung, 6, 1, 1, 4)
        self.inMieteGueltigBis = QtWidgets.QLineEdit(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inMieteGueltigBis.sizePolicy().hasHeightForWidth())
        self.inMieteGueltigBis.setSizePolicy(sizePolicy)
        self.inMieteGueltigBis.setObjectName("inMieteGueltigBis")
        self.gridLayout_2.addWidget(self.inMieteGueltigBis, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.inMieteGueltigAb = QtWidgets.QLineEdit(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inMieteGueltigAb.sizePolicy().hasHeightForWidth())
        self.inMieteGueltigAb.setSizePolicy(sizePolicy)
        self.inMieteGueltigAb.setObjectName("inMieteGueltigAb")
        self.gridLayout_2.addWidget(self.inMieteGueltigAb, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.tbMieteGueltigBis = QtWidgets.QToolButton(self.tabMiete)
        self.tbMieteGueltigBis.setObjectName("tbMieteGueltigBis")
        self.gridLayout_2.addWidget(self.tbMieteGueltigBis, 5, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 3, 1, 2)
        self.btnBoxMiete = QtWidgets.QDialogButtonBox(self.tabMiete)
        self.btnBoxMiete.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxMiete.setObjectName("btnBoxMiete")
        self.gridLayout_2.addWidget(self.btnBoxMiete, 9, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.inNettoMiete = QtWidgets.QLineEdit(self.tabMiete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inNettoMiete.sizePolicy().hasHeightForWidth())
        self.inNettoMiete.setSizePolicy(sizePolicy)
        self.inNettoMiete.setObjectName("inNettoMiete")
        self.gridLayout_2.addWidget(self.inNettoMiete, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tabMiete)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 7, 0, 1, 1)
        self.tblMieteHistorie = QtWidgets.QTableWidget(self.tabMiete)
        self.tblMieteHistorie.setObjectName("tblMieteHistorie")
        self.tblMieteHistorie.setColumnCount(0)
        self.tblMieteHistorie.setRowCount(0)
        self.gridLayout_2.addWidget(self.tblMieteHistorie, 7, 1, 1, 4)
        self.tabsWohnung.addTab(self.tabMiete, "")
        self.tabSonstEinAus = QtWidgets.QWidget()
        self.tabSonstEinAus.setObjectName("tabSonstEinAus")
        self.tabsWohnung.addTab(self.tabSonstEinAus, "")
        self.tabMietverh = QtWidgets.QWidget()
        self.tabMietverh.setObjectName("tabMietverh")
        self.tabsWohnung.addTab(self.tabMietverh, "")
        self.verticalLayout.addWidget(self.tabsWohnung)
        self.btnBoxDetails = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBoxDetails.sizePolicy().hasHeightForWidth())
        self.btnBoxDetails.setSizePolicy(sizePolicy)
        self.btnBoxDetails.setMaximumSize(QtCore.QSize(16777215, 70))
        self.btnBoxDetails.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxDetails.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxDetails.setCenterButtons(False)
        self.btnBoxDetails.setObjectName("btnBoxDetails")
        self.verticalLayout.addWidget(self.btnBoxDetails)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 1, 2, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(600, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 274, 793))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tvWohnungen = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tvWohnungen.setFont(font)
        self.tvWohnungen.setStyleSheet("")
        self.tvWohnungen.setObjectName("tvWohnungen")
        self.horizontalLayout_2.addWidget(self.tvWohnungen)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Beenden = QtWidgets.QAction(MainWindow)
        self.action_Beenden.setObjectName("action_Beenden")
        self.action_Neue_Wohnung = QtWidgets.QAction(MainWindow)
        self.action_Neue_Wohnung.setObjectName("action_Neue_Wohnung")
        self.actionWohnung_l_schen = QtWidgets.QAction(MainWindow)
        self.actionWohnung_l_schen.setObjectName("actionWohnung_l_schen")
        self.actionNeuer_Verwalter = QtWidgets.QAction(MainWindow)
        self.actionNeuer_Verwalter.setObjectName("actionNeuer_Verwalter")
        self.actionAnlagen_V_erstellen = QtWidgets.QAction(MainWindow)
        self.actionAnlagen_V_erstellen.setObjectName("actionAnlagen_V_erstellen")
        self.actionJahresuebersicht = QtWidgets.QAction(MainWindow)
        self.actionJahresuebersicht.setObjectName("actionJahresuebersicht")
        self.toolBar.addAction(self.action_Neue_Wohnung)
        self.toolBar.addAction(self.actionNeuer_Verwalter)
        self.toolBar.addAction(self.actionAnlagen_V_erstellen)
        self.toolBar.addAction(self.actionJahresuebersicht)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Beenden)

        self.retranslateUi(MainWindow)
        self.tabsWohnung.setCurrentIndex(1)
        self.tvWohnungen.clicked['QModelIndex'].connect(MainWindow.onWohnungenTreeClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wohnungsverwaltung"))
        self.grpSonst.setTitle(_translate("MainWindow", "Sonstige Angaben"))
        self.cboGarage.setItemText(0, _translate("MainWindow", "Keine Garage"))
        self.cboGarage.setItemText(1, _translate("MainWindow", "TG Stellplatz"))
        self.cboGarage.setItemText(2, _translate("MainWindow", "Stellplatz im Freien"))
        self.cboGarage.setItemText(3, _translate("MainWindow", "Garage"))
        self.lblBemerk.setText(_translate("MainWindow", "Bemerkungen: "))
        self.cbAufzug.setText(_translate("MainWindow", "Aufzug"))
        self.cbKeller.setText(_translate("MainWindow", "Keller"))
        self.label_9.setText(_translate("MainWindow", "Garage: "))
        self.grpWhg.setTitle(_translate("MainWindow", "Angaben zur Wohnung"))
        self.lblZimmer.setText(_translate("MainWindow", "Zimmer:"))
        self.label.setText(_translate("MainWindow", "Größe (qm): "))
        self.label_3.setText(_translate("MainWindow", "Balkon: "))
        self.label_2.setText(_translate("MainWindow", "EBK: "))
        self.label_7.setText(_translate("MainWindow", "Heizung: "))
        self.label_8.setText(_translate("MainWindow", "zusätzliche Merkmale: "))
        self.grpBad.setTitle(_translate("MainWindow", "Angaben zum Bad"))
        self.cbTageslicht.setText(_translate("MainWindow", "Tageslicht"))
        self.cbDusche.setText(_translate("MainWindow", "Dusche"))
        self.cbWanne.setText(_translate("MainWindow", "Badewanne"))
        self.cbBidet.setText(_translate("MainWindow", "Bidet"))
        self.grpAdresse.setTitle(_translate("MainWindow", "Adresse"))
        self.lblPlz.setText(_translate("MainWindow", "PLZ:"))
        self.lblOrt.setText(_translate("MainWindow", "Ort:"))
        self.lblStrasse.setText(_translate("MainWindow", "Straße: "))
        self.lblWhgBez.setText(_translate("MainWindow", "Bezeichnung der Wohnung: "))
        self.tabsWohnung.setTabText(self.tabsWohnung.indexOf(self.tabDetails), _translate("MainWindow", "Details"))
        self.btnTest.setText(_translate("MainWindow", "PushButton"))
        self.tabsWohnung.setTabText(self.tabsWohnung.indexOf(self.tabRechnungen), _translate("MainWindow", "Rechnungen"))
        self.tbMieteGueltigAb.setText(_translate("MainWindow", "..."))
        self.label_16.setText(_translate("MainWindow", "Bemerkung "))
        self.label_4.setText(_translate("MainWindow", "Netto-Miete "))
        self.label_10.setText(_translate("MainWindow", "Gültig bis "))
        self.label_5.setText(_translate("MainWindow", "NK-Abschlag "))
        self.tbMieteGueltigBis.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Gültig ab "))
        self.label_15.setText(_translate("MainWindow", "Historie "))
        self.tabsWohnung.setTabText(self.tabsWohnung.indexOf(self.tabMiete), _translate("MainWindow", "Miete"))
        self.tabsWohnung.setTabText(self.tabsWohnung.indexOf(self.tabSonstEinAus), _translate("MainWindow", "Sonstige Ein-/Auszahlungen"))
        self.tabsWohnung.setTabText(self.tabsWohnung.indexOf(self.tabMietverh), _translate("MainWindow", "Mietverhältnis"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Beenden.setText(_translate("MainWindow", "&Beenden"))
        self.action_Neue_Wohnung.setText(_translate("MainWindow", "&Neue Wohnung..."))
        self.actionWohnung_l_schen.setText(_translate("MainWindow", "Wohnung &löschen"))
        self.actionNeuer_Verwalter.setText(_translate("MainWindow", "Neuer &Verwalter..."))
        self.actionAnlagen_V_erstellen.setText(_translate("MainWindow", "Anlagen V erstellen..."))
        self.actionJahresuebersicht.setText(_translate("MainWindow", "Jahresübersicht"))
        self.actionJahresuebersicht.setToolTip(_translate("MainWindow", "Übersicht über die Einnahmen und Ausgaben des laufenden Jahres"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

